

services:
  db:
    image: postgres:15
    container_name: sunc_db
    restart: always
    environment:
      POSTGRES_DB: sunc_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
    - ./db_init/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    - ./db_init/02_seed_products.sql:/docker-entrypoint-initdb.d/02_seed_products.sql:ro

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/sunc_delivery

volumes:
  postgres_data: